package cr.ac.una.prograiv.aerolinea.domain;
// Generated May 15, 2017 4:34:39 PM by Hibernate Tools 4.3.1



/**
 * Avion generated by hbm2java
 */
public class Avion  implements java.io.Serializable {


     private Integer idAvion;
     private Integer anno;
     private String modelo;
     private String marca;
     private Integer cantidadPasajeros;
     private Integer filas;
     private Integer asientosXfila;

    public Avion() {
    }

    public Avion(Integer anno, String modelo, String marca, Integer cantidadPasajeros, Integer filas, Integer asientosXfila) {
       this.anno = anno;
       this.modelo = modelo;
       this.marca = marca;
       this.cantidadPasajeros = cantidadPasajeros;
       this.filas = filas;
       this.asientosXfila = asientosXfila;
    }

    public Avion(Integer idAvion, Integer anno, String modelo, String marca, Integer cantidadPasajeros, Integer filas, Integer asientosXfila) {
        this.idAvion = idAvion;
        this.anno = anno;
        this.modelo = modelo;
        this.marca = marca;
        this.cantidadPasajeros = cantidadPasajeros;
        this.filas = filas;
        this.asientosXfila = asientosXfila;
    }
    
    
   
    public Integer getIdAvion() {
        return this.idAvion;
    }
    
    public void setIdAvion(Integer idAvion) {
        this.idAvion = idAvion;
    }
    public Integer getAnno() {
        return this.anno;
    }
    
    public void setAnno(Integer anno) {
        this.anno = anno;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public Integer getCantidadPasajeros() {
        return this.cantidadPasajeros;
    }
    
    public void setCantidadPasajeros(Integer cantidadPasajeros) {
        this.cantidadPasajeros = cantidadPasajeros;
    }
    public Integer getFilas() {
        return this.filas;
    }
    
    public void setFilas(Integer filas) {
        this.filas = filas;
    }
    public Integer getAsientosXfila() {
        return this.asientosXfila;
    }
    
    public void setAsientosXfila(Integer asientosXfila) {
        this.asientosXfila = asientosXfila;
    }




}


