package cr.ac.una.prograiv.aerolinea.domain;
// Generated May 15, 2017 4:34:39 PM by Hibernate Tools 4.3.1



/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer idReserva;
     private int pkfkUsuario;
     private int pkfkVuelo;
     private Integer canAsientosReservados;
     private String numeroTarjeta;
     private Double monto;
     private int pkfkAsiento;

    public Reserva() {
    }

	
    public Reserva(int pkfkUsuario, int pkfkVuelo, int pkfkAsiento) {
        this.pkfkUsuario = pkfkUsuario;
        this.pkfkVuelo = pkfkVuelo;
        this.pkfkAsiento = pkfkAsiento;
    }
    public Reserva(int pkfkUsuario, int pkfkVuelo, Integer canAsientosReservados, String numeroTarjeta, Double monto, int pkfkAsiento) {
       this.pkfkUsuario = pkfkUsuario;
        this.pkfkVuelo = pkfkVuelo;
       this.canAsientosReservados = canAsientosReservados;
       this.numeroTarjeta = numeroTarjeta;
       this.monto = monto;
       this.pkfkAsiento = pkfkAsiento;
    }
   
    public Integer getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(Integer idReserva) {
        this.idReserva = idReserva;
    }
   
    public Integer getCanAsientosReservados() {
        return this.canAsientosReservados;
    }
    
    public void setCanAsientosReservados(Integer canAsientosReservados) {
        this.canAsientosReservados = canAsientosReservados;
    }
    public String getNumeroTarjeta() {
        return this.numeroTarjeta;
    }
    
    public void setNumeroTarjeta(String numeroTarjeta) {
        this.numeroTarjeta = numeroTarjeta;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }

    public int getPkfkUsuario() {
        return pkfkUsuario;
    }

    public void setPkfkUsuario(int pkfkUsuario) {
        this.pkfkUsuario = pkfkUsuario;
    }

    public int getPkfkVuelo() {
        return pkfkVuelo;
    }

    public void setPkfkVuelo(int pkfkVuelo) {
        this.pkfkVuelo = pkfkVuelo;
    }

    public int getPkfkAsiento() {
        return pkfkAsiento;
    }

    public void setPkfkAsiento(int pkfkAsiento) {
        this.pkfkAsiento = pkfkAsiento;
    }
   
    
    


}


