package cr.ac.una.prograiv.aerolinea.domain;
// Generated May 15, 2017 4:34:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ruta generated by hbm2java
 */
public class Ruta  implements java.io.Serializable {


     private Integer idRuta;
     private int pkfkHorario;
     private String lugarDestino;
     private String lugarSalida;
     private Double precio;
     private String duracion;

    public Ruta() {
    }

	
    public Ruta(int pkfkHorario) {
        this.pkfkHorario = pkfkHorario;
    }
    public Ruta(Integer idRuta,int pkfkHorario, String lugarDestino, String lugarSalida, Double precio, String duracion) {
       this.idRuta = idRuta;
        this.pkfkHorario = pkfkHorario;
       this.lugarDestino = lugarDestino;
       this.lugarSalida = lugarSalida;
       this.precio = precio;
       this.duracion = duracion;
    }

    
    
    
   
    public Integer getIdRuta() {
        return this.idRuta;
    }
    
    public void setIdRuta(Integer idRuta) {
        this.idRuta = idRuta;
    }

    public int getPkfkHorario() {
        return pkfkHorario;
    }

    public void setPkfkHorario(int pkfkHorario) {
        this.pkfkHorario = pkfkHorario;
    }
   
    public String getLugarDestino() {
        return this.lugarDestino;
    }
    
    public void setLugarDestino(String lugarDestino) {
        this.lugarDestino = lugarDestino;
    }
    public String getLugarSalida() {
        return this.lugarSalida;
    }
    
    public void setLugarSalida(String lugarSalida) {
        this.lugarSalida = lugarSalida;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }




}


