package cr.ac.una.prograiv.aerolinea.domain;
// Generated May 15, 2017 4:34:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombUsuario;
     private String constrasena;
     private String apellidos;
     private String correoElectronico;
     private Date fechaNacimiento;
     private String direccion;
     private String telefonoTrabajo;
     private String celular;

    public Usuario() {
    }

    public Usuario(String nombUsuario, String constrasena, String apellidos, String correoElectronico, Date fechaNacimiento, String direccion, String telefonoTrabajo, String celular) {
       this.nombUsuario = nombUsuario;
       this.constrasena = constrasena;
       this.apellidos = apellidos;
       this.correoElectronico = correoElectronico;
       this.fechaNacimiento = fechaNacimiento;
       this.direccion = direccion;
       this.telefonoTrabajo = telefonoTrabajo;
       this.celular = celular;
    }

    public Usuario(Integer idUsuario, String nombUsuario, String constrasena, String apellidos, String correoElectronico, Date fechaNacimiento, String direccion, String telefonoTrabajo, String celular) {
        this.idUsuario = idUsuario;
        this.nombUsuario = nombUsuario;
        this.constrasena = constrasena;
        this.apellidos = apellidos;
        this.correoElectronico = correoElectronico;
        this.fechaNacimiento = fechaNacimiento;
        this.direccion = direccion;
        this.telefonoTrabajo = telefonoTrabajo;
        this.celular = celular;
    }
    
    

    
    
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombUsuario() {
        return this.nombUsuario;
    }
    
    public void setNombUsuario(String nombUsuario) {
        this.nombUsuario = nombUsuario;
    }
    public String getConstrasena() {
        return this.constrasena;
    }
    
    public void setConstrasena(String constraseña) {
        this.constrasena = constraseña;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefonoTrabajo() {
        return this.telefonoTrabajo;
    }
    
    public void setTelefonoTrabajo(String telefonoTrabajo) {
        this.telefonoTrabajo = telefonoTrabajo;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }




}


