package cr.ac.una.prograiv.aerolinea.domain;
// Generated May 15, 2017 4:34:39 PM by Hibernate Tools 4.3.1



/**
 * Vuelo generated by hbm2java
 */
public class Vuelo  implements java.io.Serializable {


     private Integer idVuelo;
     private int pkfkAvion;
     private int pkfkRuta;

    public Vuelo() {
    }

    public Vuelo(int pkfkAvion, int pkfkRuta) {
       this.pkfkAvion = pkfkAvion;
       this.pkfkRuta = pkfkRuta;
    }
   
    public Integer getIdVuelo() {
        return this.idVuelo;
    }
    
    public void setIdVuelo(Integer idVuelo) {
        this.idVuelo = idVuelo;
    }

    public int getPkfkAvion() {
        return pkfkAvion;
    }

    public void setPkfkAvion(int pkfkAvion) {
        this.pkfkAvion = pkfkAvion;
    }

    public int getPkfkRuta() {
        return pkfkRuta;
    }

    public void setPkfkRuta(int pkfkRuta) {
        this.pkfkRuta = pkfkRuta;
    }
    
    




}


